config/routes.rb
Rails.application.routes.draw do

  resources :meetings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post "likes/:article_id/create" => "likes#create" # いいね

  post "likes/:article_id/destroy" => "likes#destroy" #いいね削除

  get "users/:id/likes" => "users#likes"

  get "login" => "users#login_form" #ログイン

  post "login" => "users#login" # ログインフォーム受け取り

  post "logout" => "users#logout" # ログアウト

  get 'users/index' => "users#index" #　ユーザー一覧

  post "users/create" => "users#create" #ユーザー作成

  get "users/signup" => "users#new" # ユーザー登録

  get "users/:id" => "users#show"

  get "users/:id/edit" => "users#edit"

  post "users/:id/update" => "users#update" # ユーザー更新

  # post "users/:id/destroy" => "users#destroy" #ユーザー削除


get "/" => "blogs#index" # 一覧画面

get 'articles/new' => 'articles#new' # 投稿画面

post 'create' => "articles#create" # 投稿機能

get "articles/:id" => "articles#show"

get "articles/:id/edit" => "articles#edit" #　投稿編集

post "articles/:id/update" => "articles#update" #　投稿更新

post "articles/:id/destroy" => "articles#destroy" #　投稿削除


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

validates :content, {presence: true, length: {maximum: 1000}}
validates :user_id, {presence: true}
belongs_to :user
default_scope -> { order(created_at: :desc) }

  def user
    return User.find_by(id: self.user_id)
  end

end

app/models/like.rb
class Like < ApplicationRecord

  validates :user_id, {presence: true}
  validates :article_id, {presence: true}
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :articles

  validates :name, {presence: true}
  validates :email, {presence: true, uniqueness: true}


  def articles
    return Article.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :set_current_user

def set_current_user
  @current_user = User.find_by(id: session[:user_id])
end

def authenticate_user
  if @current_user == nil
    flash[:notice] = "ログインが必要です"
    redirect_to("/login")
  end
end

def forbid_login_user
  if @current_user
    flash[:notice] = "すでにログインしています"
    redirect_to("/")
  end
end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


before_action :authenticate_user,{only:[:edit, :update, :destroy]}

def new
  @article = Article.new
end

def create
  @article = Article.new(content: params[:content],
  title: params[:title],day: params[:day],user_id: @current_user.id
)
if @article.save
  flash[:notice] = "投稿を作成しました"
  redirect_to("/")
else
  render("articles/new")
end
end

def show
  @article = Article.find_by(id: params[:id])
  @user = User.find_by(id: @article.user_id)
  @likes_count = Like.where(article_id: @article.id).count
  end


def edit
  @article = Article.find_by(id: params[:id])
end

def update
  @article = Article.find_by(id: params[:id])
  @article.content = params[:content] #name属性でparamsに代入されupdateアクションに送られる。値をparams[:content]で受け取り、投稿内容の更新をする。
  @article.title = params[:title]
  @article.day = params[:day]

  if @article.save
    flash[:notice] = "投稿を編集しました"
    redirect_to("/")
  else
    render("articles/edit")
  end
end

def destroy
  @article = Article.find_by(id: params[:id])
  @article.destroy
  flash[:notice] = "投稿を削除しました"
  redirect_to("/")
end

def ensure_corrent_user
@article = Article.find_by(id: params[:id])
  if @article.user_id != current_user.id
    flash[:notice] = "権限がありません"
    redirect("/")
  end
end

private
def article_params
  params.require(:article).permit(:text, :content, :img, :remove_img)
end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

before_action :authenticate_user,{only: [:new, :create]}

def index
  @articles = Article.page(params[:page]).per(10)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

before_action :authenticate_user
def create
  @like = Like.new(
    user_id: @current_user.id,
    article_id: params[:article_id]
  )
  @like.save
  redirect_to("/articles/#{params[:article_id]}")
end

def destroy
  @like = Like.find_by(
    user_id: @current_user.id,
    article_id: params[:article_id]
  )
  @like.destroy
  redirect_to("/articles/#{params[:article_id]}")
end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update]}

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(
    name: params[:name],
    email: params[:email],
    image_name: "default_user.jpg",
    password: params[:password]
  )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザーを登録しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/new")
    end
  end


def edit
  @user = User.find_by(id: params[:id])
end

def update
  @user = User.find_by(id: params[:id])
  @user.name = params[:name]
  @user.email = params[:email]

  if params[:image]
    @user.image_name = "#{@user.id}.jpg"
    image = params[:image]
    File.binwrite("public/user_images.jpg/#{@user.image_name}", image.read)
  end

  if @user.save
    flash[:notice] = "情報を編集しました"
    redirect_to("/users/#{@user.id}")
  else
    render("users/edit")
  end
end

def login_form
end

def login
  @user = User.find_by(email: params[:email])
  if @user && @user.authenticate(params[:password])
    session[:user_id] = @user.id
    flash[:notice] = "ログインしました"
    redirect_to("/")
  else
    @error_message = "メールアドレスまたはパスワードが間違っています"
    @email = params[:email]
    @password = params[:password]
    render("users/login_form")
  end
end

def logout
  session[:user_id] = nil
  flash[:notice] = "ログアウトしました"
  redirect_to("/login")
end

def ensure_correct_user
  if @current_user.id != params[:id].to_i
    flash[:notice] = "権限がありません"
    redirect_to("/")
  end
end

  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="main articles-new">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
<%= form_tag("/articles/#{@article.id}/update") do %>
    <div class="form">
      <div class="form-body">
        </div>

        <textarea name="title" placeholder="タイトル"><%= @article.title %></textarea>
        <textarea name="day" placeholder="開催日"><%= @article.day %></textarea>
        <textarea name="content" placeholder="記事を書いてください" rows="10" cols="50"><%= @article.content %></textarea>

        <input type="submit" value="保存" class="btn-submit">
      </div>
    </div>
<% end %>
  </div>

app/views/articles/new.html.erb
<div class="contents row">
  <a href="/">一覧にもどる</a>
  </div>
  <%= form_tag('/create', method: :post) do %>
    <h3>
      投稿する
    </h3>
    <div class="form">



      <div class="form-body">
        <% @article.errors.full_messages.each do |message| %>
        <div class ="form-error">
          <%= message %>
          </div>
          <% end %>
          <textarea name="title" placeholder="タイトル"><%= @article.title %></textarea>
          <textarea name="day" placeholder="場所"><%= @article.day %></textarea>
          <textarea name="content" placeholder="記事を書いてください" rows="10" cols="50"><%= @article.content %></textarea>
          <input type="submit" value="保存" class="btn-submit">
    </div>
    </div>
  <% end %>

app/views/articles/show.html.erb
<div class="main articles-show">
  <div class="container">
    <div class="articles-show-item">

      <div class="article-user-name">
        <img src="<%= "/user_images.jpg/#{@user.image_name}" %>">

        <%= link_to(@user.name, "/users/#{@user.id}") %>
        </div>

      <h1 class="articletitle">
        <%= @article.title %></h1>
      <div class="articleday">
      <%= @article.day %>
      </div>

      <div class="articlecontent">
        <%= @article.content %>
        </div>

        <% if Like.find_by(user_id: @current_user.id, article_id: @article.id) %>
        <%= link_to("/likes/#{@article.id}/destroy", {method: "post"}) do %>
        <span class="fa fa-heart like-btn-unlike"></span>
        <% end %>
        <% else %>
        <%= link_to("/likes/#{@article.id}/create", {method: "post"}) do %>
        <span class="fa fa-heart like-btn-unlike"></span>
        <% end %>
        <% end %>

        <%= @likes_count %>


        <div class="article-time">
        <%= @article.created_at %>
        </div>
        <div class="article-menus">
        <% if @article.user_id == @current_user.id %>

          <%= link_to("編集", "/articles/#{@article.id}/edit") %>
          <%= link_to("削除", "/articles/#{@article.id}/destroy", {method: "post"}) %>
          <% end %>
          <%= link_to("home","/") %>



          </div>
          </div>
          </div>
          </div>

app/views/blogs/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>日本非日常ツアー</title>
    <link rel="stylesheet" href="stylesheet.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  </head>
  <body>

<ul>
  <li>
    <h1 class="list_article">
  <% @articles.each do |article| %>
    </h1>
    <div class="article-left">
      <img src="<%="/user_images.jpg/#{article.user.image_name}"%>">
      </div>
      <div class="article-user-name">
        <%= link_to(article.user.name, "/users/#{article.user.id}") %>
      </div>
    <h2 class="title">
      <%=  link_to(article.title, "/articles/#{article.id}") %>
    </h2>
    <!<% if article.image != "" %>>
    <p class="index-day">
      <%= article.day %></p>
    <% end %>

    <p><%= article.created_at %></p>
  </li>
  <% end %>
</ul>

<%= paginate(@articles) %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>nihon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加　Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="rgba">
    <header>
      <%= link_to("日本非日常ツアー","/", {class: "header"}) %>
      </header>
    <div class="header-logo">B級スポットや知られざる観光地を投稿するサービスです！
    <li>随時更新中！</li>
    </div>
      <div class="container">
        <div class="header-left">
        </div>
        </div>
      <div class="logo">
        <ul class="header-menus">
          <% if @current_user %>

          <li>
        <%= link_to(@current_user.name, "/users/#{@current_user.id}") %>
          </li>
        <%= link_to("home","/" , {class: "home"}) %>
        <%= link_to("新規投稿", "/articles/new", {class: "new"}) %>
        <%= link_to("ユーザー一覧", "/users/index", {class: "usersindex"}) %>
        <%= link_to("ログアウト", "/logout", {method: :post}) %>

        <% else %>
        <%= link_to("home","/" , {class: "home"}) %>
        <%= link_to("新規登録", "/users/signup", {class: "signup"}) %>
        <%= link_to("ログイン", "/login") %>

        <% end %>

      </ul>
        </div>
        </div>

        <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
          </div>


          <% end %>
    <%= yield %>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<%= month_calender events: @meetings do |date,meetings| %>
    <%= date %>

    <% meetings.each do |meeting| %>
      <div>
        <%= meeting.name %>
      </div>
      <% end %>
      <% end %> 

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">アカウント編集</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>

        <%= form_tag("/users/#{@user.id}/update", {multipart: true}) do %>
          <p>ユーザー名</p>
          <input name="name" value="<%= @user.name %>">
          <p>画像</p>
          <input name="image" type="file">
          <p>メールアドレス</p>
          <input name="email" value="<%= @user.email %>">
          <input type="submit" value="保存">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">ユーザー一覧</h1>
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-left">
          <img src="<%="/user_images.jpg/#{user.image_name}"%>">
        </div>
        <div class="user-right">
          <%= link_to(user.name, "/users/#{user.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/likes.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <img src="<%= "/user_images.jpg/#{@user.image_name}" %>">
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("編集", "/users/#{@user.id}/edit") %>
      <% end %>
    </div>

    <ul class="user-tabs">
      <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>

    <% @likes.each do |like| %>

      <% article = Article.find_by(id: like.article_id) %>

      <div class="articles-index-item">
        <div class="article-left">
          <img src="<%= "/user_images.jpg/#{article.user.image_name}" %>">
        </div>
        <div class="article-right">
          <div class="article-user-name">
            <%= link_to(article.user.name, "/users/#{article.user.id}") %>
          </div>
          <%= link_to(article.content, "/articles/#{article.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ログインフォーム</div>
    <div class="form users-form">
      <div class="form-body">

        <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>

        <%= form_tag("/login") do %>

        <p>メールアドレス</p>
        <input name="email" value="<%= @email %>">

        <p>パスワード</p>
        <input type="password" name="password" value="<%= @password %>">
        <input type="submit" value="ログイン">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    <div class="form users-form">
      <div class="form-body">

        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>

        <%= form_tag("/users/create") do %>
          <p>ユーザー名</p>
          <input name="name" value="<%= @user.name %>">
          <p>メールアドレス</p>
          <input name="email" value="<%= @user.email %>">
          <p>パスワード</P>
          <input type="password" name="password"
          value="<%= @user.password %>"> 
          <input type="submit" value="新規登録">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <img src="<%="/user_images.jpg/#{@user.image_name}"%>">
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
      <%= link_to("編集", "/users/#{@user.id}/edit") %>
      <% end %>

      <ul class="user-tabs">
      <li class="active"><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>
    
      <% @user.articles.each do |article| %>
      <div class="articles-index-item">

        <div class="article-left">
          <img src="<%="/user_images.jpg/#{@user.image_name}"%>">
          </div>
          <div class="article-right">
            <%= link_to(article.user.name, "/users/#{article.user.id}") %>
            </div>
          <%= link_to(article.content, "/articles/#{article.id}") %>
        </div>
      </div>
    </div>
    <% end %>
  </div>